Repository resurrecting-open-source-projects/scrot, pull requests merged in 2021-07, with the labels that each got.

#97 autotools improvement
  README.md
  configure.ac
  scrot.spec
  src/Makefile.am
  src/options.c
Labels: completed

#107 remove acinclude.m4
  acinclude.m4
Labels: good proposal

#106 remove unused __attribute__ macro
  src/scrot.h
Labels: good proposal

#103 delete scrot.spec
  Makefile.am
  scrot.spec
Labels: good proposal

#105 use strndup to provide new_text
  src/note.c
Labels: good proposal, has conflict, has pending dependency
